### ISSUE TITLE
R-studio to spark standalone cluster connection using cassandra 

### ISSUE THREAD

**Issue by peddollakishore** [AkhilNairAmey/crassy#1]
Hi @AkhilNairAmey can you please tell me how to connect R to standalone cluster using cassandra

**Comment by AkhilGNair** [comment]
Can you initialise a `sparklyr` connection?  The cassandra connection comes after the `sparklyr` connection has already been established

**Comment by peddollakishore** [comment]
Hi @AkhilNairAmey ya git it Akhil but i am facing another issue,

while running the below code i am waiting long to execute the code.
`
>library(sparklyr)
>library(dplyr)
>library(crassy)
>Sys.setenv(SPARK_HOME='/home/ubuntu/spark')
>sc <- spark_connect(master = "spark://XXX.XXX.XXX:7077")
>spark_load_cassandra_table(sc, "test", "kv", "test_tbl", partition_filter = FALSE, select_cols = FALSE, cache_table = FALSE)
**Waiting......**
`

**Comment by peddollakishore** [comment]
This code for local spark cluster it is executed successfully.
`
>library(sparklyr)
>library(dplyr)
>library(crassy)
>Sys.setenv(SPARK_HOME='/home/ubuntu/spark')
>sc <- spark_connect(master = "local")
> spark_load_cassandra_table(sc, "test", "kv", "spkr_tbl_name", partition_filter = FALSE, select_cols = FALSE, cache_table = FALSE)
Source:   query [3 x 2]
Database: spark connection master=local[2] app=sparklyr local=TRUE
A tibble: 3 x 2
    key value
  <chr> <int>
1  key1     1
2  key3     3
3  key2     2`

**Comment by AkhilGNair** [comment]
It is hard to know without being able to recreate the issue, but you may not have set the the config variable `spark.cassandra.connection.host` to point your spark cluster to your cassandra cluster.  The config variable is passed to `sparklyr`.

It would work in the second case as they're all collocated locally.

**Comment by peddollakishore** [comment]
Hi @AkhilNairAmey Thank you for reply.

below is the code for spark cluster connection using cassandra host, here is also same waiting.


library(pipeR)
library(sparklyr)
library(dplyr)


Sys.setenv(SPARK_HOME='/home/ubuntu/spark')
sc <- spark_connect(master = "spark://XXXXXXXXX:7077")
**Executed**

sparkSession <- invoke_static(sc, "org.apache.spark.sql.SparkSession", "builder") %>>%
  invoke("config", "spark.cassandra.connection.host", "XXXXXXXX:9042") %>>%
  invoke("getOrCreate")
**Executed**

cass_df <- invoke(sparkSession, "read") %>>% 
  invoke("format", "org.apache.spark.sql.cassandra") %>>%
  invoke("option", "keyspace", "test") %>>% invoke("option", "table", "kv") %>>%
  invoke("load")
**Executed** 

bbh_tbl <- sparklyr:::spark_partition_register_df(sc, cass_df, "bbh", 0, TRUE)
**Waiting...........**

**Comment by AkhilGNair** [comment]
Not sure if it will solve your problem, but the `spark.cassandra.connection.host` shouldn't have a port specification as far as I'm aware. Either way, I'm going to assume this is a networking issue, more than a library issue

**Comment by peddollakishore** [comment]
i removed the port in spark.cassandra.connection.host, still it is long waiting mode only
